// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9mVnss44uQ1wkP4wFC6B7QJB3jCtx3Gk',
    appId: '1:354219393052:web:7848e27ae28c625f0a9fd9',
    messagingSenderId: '354219393052',
    projectId: 'cart-order-b51d9',
    authDomain: 'cart-order-b51d9.firebaseapp.com',
    storageBucket: 'cart-order-b51d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGk53gvZ5cDuafWn3eSDkyXzA4wYWvlag',
    appId: '1:354219393052:android:6a5af22b790f69250a9fd9',
    messagingSenderId: '354219393052',
    projectId: 'cart-order-b51d9',
    storageBucket: 'cart-order-b51d9.firebasestorage.app',
  );
}
